name: "Close PR on Failure"

on:
  pull_request:
    branches: ["dev"]
    types: [opened, synchronize, reopened]

jobs:

  validate-commit-message:
    runs-on: ubuntu-latest
    outputs:
      commit_status: ${{ steps.check-commit.outcome }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Fetch all history for all tags and branches
        run: git fetch --no-tags --prune --depth=50
    
      - name: Get the last non-merge commit
        id: last_commit
        run: |
          COMMIT_HASH=$(git log --no-merges -n 1 --format="%cn")
          COMMIT_AUTHOR=$(git log --no-merges -n 1 --format="%an")
          COMMIT_MESSAGE=$(git log --no-merges -n 1 --format="%s")
          echo "Last commit hash: $COMMIT_HASH"
          echo "Last commit author: $COMMIT_AUTHOR"
          echo "Last commit message: $COMMIT_MESSAGE"
          echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV
          echo "COMMIT_AUTHOR=$COMMIT_AUTHOR" >> $GITHUB_ENV
          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV
    
      - name: Use the commit data
        run: |
          echo "Using commit $COMMIT_HASH by $COMMIT_AUTHOR with message: $COMMIT_MESSAGE"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check commit messages
        id: check-commit
        run: |

          echo "Fetching the most recent non-merge commit..."
          COMMIT_MSG=$(git log --no-merges -n 1 --pretty=format:"%H %an %s")
          echo "Fetched commit message: $COMMIT_MSG"

          COMMIT_MSG=$(git log --no-merges -n 5)
          echo $COMMIT_MSG
          echo $(git log --no-merges -n 1 --pretty=format:"%H %an %s")
          KEYWORDS='["1","2","3"]'
          URL_PATTERN='https://well-check.atlassian.net'
          if [[ (! "$COMMIT_MSG" =~ "fix" && ! "$COMMIT_MSG" =~ "feat" && ! "$COMMIT_MSG" =~ "chore") || (! "$COMMIT_MSG" =~ $URL_PATTERN) ]]; then
            echo "Commit message validation failed."
            echo "outcome=fail" >> $GITHUB_OUTPUT
          else
            echo "outcome=success" >> $GITHUB_OUTPUT
          fi
          echo $commit_status

  build-and-test:
    needs: validate-commit-message
    if: needs.validate-commit-message.outputs.commit_status == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        id: install
        run: |
          npm install
          echo "outcome=success" >> $GITHUB_OUTPUT
          
        continue-on-error: true

      - name: Run lint
        id: lint
        if: steps.install.outcome == 'success'
        run: npm run lint
        continue-on-error: true

      - name: Run tests
        id: test
        if: steps.lint.outcome == 'success'
        run: npm test
        continue-on-error: true
          
  comment-and-close:
    needs: [validate-commit-message, build-and-test]
    if: ${{ needs.build-and-test.outputs.FAILED_STEP }} != '' ||
    runs-on: ubuntu-latest
    steps:
      - name: Leave comment on PR
        uses: peter-evans/create-or-update-comment@v4.0.0
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: "Failed at steps: ${{ needs.build-and-test.outputs.FAILED_STEP }}"
          reactions: '+1'
