name: "Close PR on Failure"

on:
  pull_request:
    branches: ["dev"]
    types: [opened, synchronize, reopened]
jobs:
  validate-commit-message:
    runs-on: ubuntu-latest
    outputs:
      commit_status: ${{ steps.check-commit.outcome }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Check commit messages
        id: check-commit
        run: |
          COMMIT_MSG=$(git log --no-merges -n 1)
          URL_PATTERN='https://well-check.atlassian.net'

          echo "Commit Message: $COMMIT_MSG"
          echo "URL Pattern: $URL_PATTERN"
          
          # Check individual conditions
          if ! [[ $COMMIT_MSG =~ "fix" || $COMMIT_MSG =~ "feat" || $COMMIT_MSG =~ "chore" ]]; then
            echo "Keyword condition failed."
            echo "Keyword condition failed." >> $GITHUB_STEP_SUMMARY
          fi
          if ! [[ $COMMIT_MSG =~ $URL_PATTERN ]]; then
            echo "URL pattern condition failed."
            echo "URL pattern condition" >> $GITHUB_STEP_SUMMARY
          fi
          

          if [[ $COMMIT_MSG =~ fix|feat|chore ]] && [[ $COMMIT_MSG =~ $URL_PATTERN ]]; then
            echo "outcome=success" >> $GITHUB_OUTPUT
          else
            echo "Commit message validation failed."
            echo "outcome=fail" >> $GITHUB_OUTPUT
          fi
          
          echo message=$(cat $GITHUB_STEP_SUMMARY) >> $GITHUB_OUTPUT
          
      - name: Leave comment on PR
        if: steps.check-commit.outputs.outcome == 'fail' || failure()
        uses: peter-evans/create-or-update-comment@v4.0.0
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{steps.check-commit.outputs.message}}
          reactions: '+1'  
          
      - name: Close Pull
        if: steps.check-commit.outputs.outcome == 'fail' || failure()
        uses: peter-evans/close-pull@v3
        with:
          pull-request-number: 1
          comment: "커밋 메시지가 검증되지 않았습니다. 메시지를 확인해주세요"
          delete-branch: false
