name: "Close PR on Failure"

on:
  pull_request:
    branches: ["dev"]
    types: [opened, synchronize, reopened]

env:
  test: valuse
jobs:
  validate-commit-message:
    runs-on: ubuntu-latest
    outputs:
      commit_status: ${{ steps.check-commit.outcome }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Check commit messages
        id: check-commit
        run: |
          COMMIT_MSG=$(git log --no-merges -n 1)
          echo $COMMIT_MSG
          COMMIT_MSG=$(git log --no-merges -n 1 --pretty=format:%s)
          echo $COMMIT_MSG
          echo $(git log --no-merges -n 1 --pretty=format:%s)
          URL_PATTERN='https://well-check.atlassian.net'

          if [[ (! $COMMIT_MSG =~ "fix" && ! $COMMIT_MSG =~ "feat" && ! $COMMIT_MSG =~ "chore") || (! $COMMIT_MSG =~ $URL_PATTERN) ]]; then
            echo "Commit message validation failed."
            echo "outcome=fail" >> $GITHUB_OUTPUT
          else
            echo "outcome=success" >> $GITHUB_OUTPUT
          fi

          
          echo "asdasddsaasd" >> $GITHUB_STEP_SUMMARY
          echo ${{$GITHUB_STEP_SUMMARY}}
          
          outcome=tesdt
          echo $outcome
          echo $commit_status
          echo $test
          echo ${{env.test}}

          echo "test=das;kdls;ad" >> $GITHUB_ENV
          echo $test
          echo ${{env.test}}

          echo $test
          echo ${{env.test}}

  build-and-test:
    needs: validate-commit-message
    if: needs.validate-commit-message.outputs.commit_status == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        id: install
        run: |
          npm install
          echo ${{needs.validate-commit-message.outputs.commit_status}}
          echo "outcome=success" >> $GITHUB_OUTPUT
          
          echo "asdasddsaasd" >> $GITHUB_STEP_SUMMARY
          echo ${{$GITHUB_STEP_SUMMARY}}
        continue-on-error: true

      - name: Run lint
        id: lint
        if: steps.install.outcome == 'success'
        run: npm run lint
        continue-on-error: true

      - name: Run tests
        id: test
        if: steps.lint.outcome == 'success'
        run: npm test
        continue-on-error: true
          
  comment-and-close:
    needs: [validate-commit-message, build-and-test]
    if: ${{ needs.build-and-test.outputs.FAILED_STEP }} != '' ||
    runs-on: ubuntu-latest
    steps:
      - name: Leave comment on PR
        uses: peter-evans/create-or-update-comment@v4.0.0
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: "Failed at steps: ${{ needs.build-and-test.outputs.FAILED_STEP }} ${{$GITHUB_STEP_SUMMARY}}"
          reactions: '+1'
